//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AlgorithmFactory.h
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#if !defined(_ALGORITHMFACTORY_H)
#define _ALGORITHMFACTORY_H

#include "IFactory.h"

class AlgorithmFactory : public IFactory {
};

#endif  //_ALGORITHMFACTORY_H
