//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AProcessingTemplate.h
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#if !defined(_APROCESSINGTEMPLATE_H)
#define _APROCESSINGTEMPLATE_H


class AProcessingTemplate {
public:
    void StartProcessing();
private:
    void LoadImage(int string path);
    void ProcessImage();
    void Classify();
    void CreateReport();
};

#endif  //_APROCESSINGTEMPLATE_H
