//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AProcessingTemplate.cpp
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#include "AProcessingTemplate.h"

void AProcessingTemplate::StartProcessing() {

}

void AProcessingTemplate::LoadImage(int string path) {

}

void AProcessingTemplate::ProcessImage() {

}

void AProcessingTemplate::Classify() {

}

void AProcessingTemplate::CreateReport() {

}

