//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IAlgorithm.h
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#if !defined(_IALGORITHM_H)
#define _IALGORITHM_H


class IAlgorithm {
public:
    void Start();
};

#endif  //_IALGORITHM_H
