//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IAlgorithm.cpp
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#include "IAlgorithm.h"

void IAlgorithm::Start() {

}

