//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IFactory.h
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#if !defined(_IFACTORY_H)
#define _IFACTORY_H


class IFactory {
public:
    void CreateAlgorithm(int string type);
};

#endif  //_IFACTORY_H
