//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IFactory.cpp
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#include "IFactory.h"

void IFactory::CreateAlgorithm(int string type) {

}

