//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IUIInfo.cpp
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#include "IUIInfo.h"

void IUIInfo::GetPhasesNames() {

}

void IUIInfo::GetAlgorithmList(int string phaseName) {

}

