//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IUIInfo.h
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#if !defined(_IUIINFO_H)
#define _IUIINFO_H


class IUIInfo {
public:
    void GetPhasesNames();
    void GetAlgorithmList(int string phaseName);
};

#endif  //_IUIINFO_H
