//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Node.cpp
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#include "Node.h"

void Node::Node<T>(int string name) {

}

void Node::Node<T>(int string nodeName, int string objName, int T* object) {

}

int Node::addObject(int string name, int T* object) {

}

int Node::addNextRef(int Node<T>* ref) {

}

int Node::addPreviousRef(int Node<T>* ref) {

}

string Node::getNodeName() {

}

string[] Node::getObjNames() {

}

T* Node::getObject(int string name) {

}

T[]* Node::getObjects() {

}

Node<T>* Node::getNextRef(int string nodeName) {

}

Node<T>* Node::getNextRef(int unsigned int number) {

}

vector<Node<T>*> Node::getNextRefs() {

}

Node<T>* Node::getPreviousRef(int string nodeName) {

}

Node<T>* Node::getPreviousRef(int unsigned int number) {

}

vector<Node<T>*> Node::getPreviousRefs() {

}

unsigned int Node::getNextRefsNumber() {

}

unsigned int Node::getPreviousRefsNumber() {

}

int Node::removeObject(int string name) {

}

int Node::removeAllObjects() {

}

int Node::removeNextRef(int string nodeName) {

}

int Node::removeNextRef(int unsigned int number) {

}

int Node::removePreviousRef(int string number) {

}

int Node::removePreviousRef(int unsigned int number) {

}

