//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProcessingTemplate.h
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#if !defined(_PROCESSINGTEMPLATE_H)
#define _PROCESSINGTEMPLATE_H

#include "AProcessingTemplate.h"
#include "IUIInfo.h"

class ProcessingTemplate : public AProcessingTemplate, public IUIInfo {
};

#endif  //_PROCESSINGTEMPLATE_H
