//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Serializable.h
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#if !defined(_SERIALIZABLE_H)
#define _SERIALIZABLE_H


class Serializable {
public:
    void serialize();
};

#endif  //_SERIALIZABLE_H
