//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Serializable.cpp
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#include "Serializable.h"

void Serializable::serialize() {

}

