//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SPGraph.h
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#if !defined(_SPGRAPH_H)
#define _SPGRAPH_H

#include "Serializable.h"

template < T : Class> class SPGraph : public Serializable {
public:
    void SPGraph<T>(int string startNodeName, int string endNodeName);
    int addSubSPGraph(int SPGraph* spg, int string targetNodeName);
    int addSubSPGraph(int SPGraph* spg, int string startNodeName, int string endNodeName);
    int addNode(int string name, int string targetNodeName);
    int addNode(int string name, int string startNodeName, int string endNodeName);
    int addEndNode(int string name);
    Node<T>* getStartNode();
    Node<T>* getCurNode();
    Node<T>* getEndNode();
    Node<T>* getNode(int string name);
    unsigned int getSize();
    int removeNode(int string name);
    int removeAll();
private:
    Node<T>* start;
    Node<T>* end;
    Node<T>* currentNodeRef;
    unsigned int size;
};

#endif  //_SPGRAPH_H
