//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SPGraph.cpp
//  @ Date : 02.04.2014
//  @ Author : 
//
//


#include "SPGraph.h"

void SPGraph::SPGraph<T>(int string startNodeName, int string endNodeName) {

}

int SPGraph::addSubSPGraph(int SPGraph* spg, int string targetNodeName) {

}

int SPGraph::addSubSPGraph(int SPGraph* spg, int string startNodeName, int string endNodeName) {

}

int SPGraph::addNode(int string name, int string targetNodeName) {

}

int SPGraph::addNode(int string name, int string startNodeName, int string endNodeName) {

}

int SPGraph::addEndNode(int string name) {

}

Node<T>* SPGraph::getStartNode() {

}

Node<T>* SPGraph::getCurNode() {

}

Node<T>* SPGraph::getEndNode() {

}

Node<T>* SPGraph::getNode(int string name) {

}

unsigned int SPGraph::getSize() {

}

int SPGraph::removeNode(int string name) {

}

int SPGraph::removeAll() {

}

